sudo: false
language: node_js
node_js: 14
cache: npm
branches:
  only: master # build master branch only
script: 
  - npm run build # generate static files
deploy:
  provider: pages
  target_branch: 'gh-pages'
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
